### ISSUE TITLE
reference to "exceptions.py" in api_token.py

### ISSUE THREAD

**Issue by gymshoe** [zoltan-fedor/yolink-integration#1]
In api_token.py, you make a reference to "exception_class", which is never defined.  Perhaps this is defined in "exceptions.py" which you mention in a comment above the exception_class reference:
"    # map the response codes to exception classes defined in exceptions.py:   "

Could you share your exceptions.py, or otherwise explain?
Thank you.

**Comment by zoltan-fedor** [comment]
What do you mean? `exception_class` is defined right there [on the previous line](https://github.com/zoltan-fedor/yolink-integration/blob/master/api_token.py#L143):

```
        exception_class = exceptions.get(result.status_code, AIClientError)

        raise exception_class(url=result.url,
                              status=result.status_code,
                              ai_service=self.service_name,  # type: ignore
                              content=response_content)
```

**Comment by gymshoe** [comment]
I'm so embarrassed; I'm. not sure how I transposed that. 
I meant I can't find "AIClientError" being defined...  Can you direct me to a source for that?
Thank you for responding.

**Comment by zoltan-fedor** [comment]
It has been added now, see https://github.com/zoltan-fedor/yolink-integration/commit/a4ad02225bd645167d939f8cfad4333b3a991313

**Comment by gymshoe** [comment]
Thank you !
